/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** Represents a button press event */
export interface ButtonPressEvent {
  button: ButtonType
}

/** Represents a button release event */
export interface ButtonReleaseEvent {
  button: ButtonType
}

/** Represents the type of button event */
export declare const enum ButtonType {
  Left = 'Left',
  Right = 'Right',
  Middle = 'Middle',
  Unknown = 'Unknown',
}

/** Display size information */
export interface DisplaySize {
  width: number
  height: number
}

/** Represents the type of event */
export declare const enum EventTypeValue {
  KeyPress = 'KeyPress',
  KeyRelease = 'KeyRelease',
  MouseMove = 'MouseMove',
  ButtonPress = 'ButtonPress',
  ButtonRelease = 'ButtonRelease',
  Wheel = 'Wheel',
}

/** Get the size of the main display */
export declare function getDisplaySize(): DisplaySize

/**
 * Checks that input simulation is available in the current environment.
 *
 * On X11, `rdev` checks display access. On Wayland, this creates one reusable
 * virtual input device through `/dev/uinput`, which requires write access.
 */
export declare function initSimulation(): void

/** Represents an input event */
export interface InputEvent {
  /** The type of event */
  eventType: EventTypeValue
  /** Key press data (only present for KeyPress events) */
  keyPress?: KeyPressEvent
  /** Key release data (only present for KeyRelease events) */
  keyRelease?: KeyReleaseEvent
  /** Mouse move data (only present for MouseMove events) */
  mouseMove?: MouseMoveEvent
  /** Button press data (only present for ButtonPress events) */
  buttonPress?: ButtonPressEvent
  /** Button release data (only present for ButtonRelease events) */
  buttonRelease?: ButtonReleaseEvent
  /** Wheel data (only present for Wheel events) */
  wheel?: WheelEvent
  /** Optional name of window (platform-dependent) */
  name?: string
  /** Timestamp of the event */
  time: number
}

/** Checks if a KeyCode is a modifier key */
export declare function isModifierKey(keyCode: KeyCode): boolean

/** Represents keyboard keys */
export declare const enum KeyCode {
  Alt = 'Alt',
  AltGr = 'AltGr',
  Backspace = 'Backspace',
  CapsLock = 'CapsLock',
  ControlLeft = 'ControlLeft',
  ControlRight = 'ControlRight',
  Delete = 'Delete',
  DownArrow = 'DownArrow',
  End = 'End',
  Escape = 'Escape',
  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
  Home = 'Home',
  LeftArrow = 'LeftArrow',
  MetaLeft = 'MetaLeft',
  MetaRight = 'MetaRight',
  NumLock = 'NumLock',
  PageDown = 'PageDown',
  PageUp = 'PageUp',
  Return = 'Return',
  RightArrow = 'RightArrow',
  ShiftLeft = 'ShiftLeft',
  ShiftRight = 'ShiftRight',
  Space = 'Space',
  Tab = 'Tab',
  UpArrow = 'UpArrow',
  PrintScreen = 'PrintScreen',
  ScrollLock = 'ScrollLock',
  Pause = 'Pause',
  Insert = 'Insert',
  BackQuote = 'BackQuote',
  Num1 = 'Num1',
  Num2 = 'Num2',
  Num3 = 'Num3',
  Num4 = 'Num4',
  Num5 = 'Num5',
  Num6 = 'Num6',
  Num7 = 'Num7',
  Num8 = 'Num8',
  Num9 = 'Num9',
  Num0 = 'Num0',
  Minus = 'Minus',
  Equal = 'Equal',
  KeyQ = 'KeyQ',
  KeyW = 'KeyW',
  KeyE = 'KeyE',
  KeyR = 'KeyR',
  KeyT = 'KeyT',
  KeyY = 'KeyY',
  KeyU = 'KeyU',
  KeyI = 'KeyI',
  KeyO = 'KeyO',
  KeyP = 'KeyP',
  LeftBracket = 'LeftBracket',
  RightBracket = 'RightBracket',
  KeyA = 'KeyA',
  KeyS = 'KeyS',
  KeyD = 'KeyD',
  KeyF = 'KeyF',
  KeyG = 'KeyG',
  KeyH = 'KeyH',
  KeyJ = 'KeyJ',
  KeyK = 'KeyK',
  KeyL = 'KeyL',
  SemiColon = 'SemiColon',
  Quote = 'Quote',
  BackSlash = 'BackSlash',
  IntlBackslash = 'IntlBackslash',
  KeyZ = 'KeyZ',
  KeyX = 'KeyX',
  KeyC = 'KeyC',
  KeyV = 'KeyV',
  KeyB = 'KeyB',
  KeyN = 'KeyN',
  KeyM = 'KeyM',
  Comma = 'Comma',
  Dot = 'Dot',
  Slash = 'Slash',
  KpReturn = 'KpReturn',
  KpMinus = 'KpMinus',
  KpPlus = 'KpPlus',
  KpMultiply = 'KpMultiply',
  KpDivide = 'KpDivide',
  Kp0 = 'Kp0',
  Kp1 = 'Kp1',
  Kp2 = 'Kp2',
  Kp3 = 'Kp3',
  Kp4 = 'Kp4',
  Kp5 = 'Kp5',
  Kp6 = 'Kp6',
  Kp7 = 'Kp7',
  Kp8 = 'Kp8',
  Kp9 = 'Kp9',
  KpDelete = 'KpDelete',
  Function = 'Function',
  Unknown = 'Unknown',
}

/** Represents a key press event */
export interface KeyPressEvent {
  key: KeyCode
}

/** Represents a key release event */
export interface KeyReleaseEvent {
  key: KeyCode
}

/** Represents a mouse move event */
export interface MouseMoveEvent {
  x: number
  y: number
}

/** Represents normalized modifier keys for shortcut handling */
export declare const enum NormalizedModifier {
  Ctrl = 'Ctrl',
  Shift = 'Shift',
  Alt = 'Alt',
  Meta = 'Meta',
}

/** Normalizes a KeyCode to its modifier name if it's a modifier key */
export declare function normalizeKeyName(keyCode: KeyCode): string

/** Simulate an input event */
export declare function simulateEvent(event: InputEvent): void

/**
 * Start listening for input events.
 *
 * The callback's return value is ignored. Only one listener may run at a
 * time; calling this while a listener is active returns an error.
 *
 * X11 uses `rdev::listen`. Linux Wayland reads physical input devices through
 * evdev and requires persistent read access to `/dev/input/event*`. Native
 * failures are reported through `on_error` when provided; otherwise they are
 * written to stderr.
 *
 * The listener holds the Node.js event loop alive until `stopListener()` is
 * called or the listen loop fails. The X11 `rdev` hook cannot be unhooked and
 * cannot restart after stop. The Wayland evdev loop exits after stop and may
 * be started again.
 */
export declare function startListener(callback: (arg: InputEvent) => void, onError?: ((arg: string) => void) | undefined | null): void

/**
 * Stop the active input event listener, if any.
 *
 * Returns `true` when a listener was running and is now stopped. After
 * stopping, the event loop is no longer held alive. Wayland can restart;
 * the X11 `rdev` hook cannot be restarted while it remains blocked.
 */
export declare function stopListener(): boolean

/** Converts a string key representation to its KeyCode */
export declare function stringKeyToKeycode(key: string): KeyCode | null

/** Represents a wheel event */
export interface WheelEvent {
  deltaX: number
  deltaY: number
}
